# Generated by Django 5.0.2 on 2024-02-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='object_id',
        ),
        migrations.AddField(
            model_name='person',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='main_app.wish'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='main_app.wish'),
        ),
    ]
