# Generated by Django 5.0.2 on 2024-02-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_wish_content_type_remove_wish_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('entry', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colours', models.CharField(blank=True, max_length=100)),
                ('cake', models.CharField(blank=True, max_length=100)),
                ('dietary', models.CharField(blank=True, max_length=100)),
                ('flowers', models.CharField(blank=True, max_length=100)),
                ('brands', models.CharField(blank=True, max_length=300)),
                ('likes_surprises', models.BooleanField(blank=True)),
                ('drinks_alcohol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='wish',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='wish',
            name='images',
            field=models.ManyToManyField(blank=True, to='main_app.photo'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.ManyToManyField(blank=True, to='main_app.note'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.ManyToManyField(blank=True, to='main_app.note'),
        ),
        migrations.AddField(
            model_name='person',
            name='things',
            field=models.ManyToManyField(blank=True, to='main_app.thing'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='things',
            field=models.ManyToManyField(blank=True, to='main_app.thing'),
        ),
        migrations.AddField(
            model_name='person',
            name='userinfo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='main_app.userinfo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userinfo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='main_app.userinfo'),
        ),
    ]
