# Generated by Django 5.0.2 on 2024-02-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_note_thing_userinfo_alter_wish_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='userinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='main_app.userinfo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='main_app.userinfo'),
        ),
    ]
