# Generated by Django 5.0.2 on 2024-02-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_person_userinfo_alter_userprofile_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='drinks_alcohol',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], default=None, max_length=10, null=True),
        ),
    ]
