# Generated by Django 5.0.2 on 2024-02-23 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_userinfo_drinks_alcohol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='things',
        ),
        migrations.RemoveField(
            model_name='person',
            name='things',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userinfo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='userinfo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='people',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='brands',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cake',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='colours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='drinks_alcohol',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flowers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes_surprises',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.person'),
        ),
        migrations.AddField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
