# Generated by Django 5.0.2 on 2024-02-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_userprofile_notes_remove_person_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='brands',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cake',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='colours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dietary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='drinks_alcohol',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='flowers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='likes_surprises',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='likes_surprises',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], default=None, max_length=10, null=True),
        ),
    ]
