# Generated by Django 5.0.2 on 2024-02-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_person_brands_person_cake_person_colours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.photo'),
        ),
    ]
