# Generated by Django 5.0.2 on 2024-03-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='url',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
